### ISSUE TITLE
Marko's Magic Football (Mega CD) Glitchy map

### ISSUE THREAD

**Issue by benderscruffy** [jsgroth/jgenesis#101]
![image](https://github.com/jsgroth/jgenesis/assets/2696404/1374e37e-8908-4d9b-9003-d599ddacbb6d)

**Comment by jsgroth** [comment]
Based on the Genesis Plus GX issue where this was reported and fixed there, this depends on the same behavior as the failing word RAM test in #105. If the sub CPU writes to word RAM while it's in 2M mode and owned the main CPU, the sub CPU needs to halt until the main CPU transfers word RAM ownership back to the sub CPU.

**Comment by jsgroth** [comment]
Fixed by the word RAM changes made for #105:
![marko](https://github.com/jsgroth/jgenesis/assets/1137683/9e29b127-b172-4923-a329-76ee2894594b)
