### ISSUE TITLE
NHL 96 (USA, Europe).md black screen after choosing teams

### ISSUE THREAD

**Issue by benderscruffy** [jsgroth/jgenesis#107]

**Comment by jsgroth** [comment]
The game seems to expect there to be 8KB of SRAM mapped to $200001-$203FFF (odd addresses) but this isn't specified in the cartridge header so the emulator doesn't give it any SRAM. This game will have to be detected at load time and special cased, much like most of the games that have EEPROM chips (where the cartridge header alone never contains enough information to know which chip to use and how to map it).
