### ISSUE TITLE
[QUESTION] what is the hardware code for Sega 32X ?

### ISSUE THREAD

**Issue by Tartifless** [jsgroth/jgenesis#131]
Hello,

I ran the -h parameter, but i do not see a specific hardware code for 32X, should it be also Genesis ? How do a differentiate between running genesis and 32X ?

Regards. Ben

**Comment by jsgroth** [comment]
Apologies, it looks like I forgot to update the help text for the `--hardware` flag.  `--hardware Sega32X` forces 32X mode, and I'll fix the help text for the next release.

**Comment by Tartifless** [comment]
Thanks !
