### ISSUE TITLE
[FEATURE REQUEST] hotkey to exit JGenesis

### ISSUE THREAD

**Issue by Tartifless** [jsgroth/jgenesis#140]
Hello,

I am currently getting acquainted with the new input settings and hotkeys settings.

I see that the hotkey for exit does exit the emulated game, but i cannot seem to find a way to exit JGenesis, would it be possible to either add a hotkey to close properly JGenesis or a setting to close JGenesis when exiting a game ?

**Comment by jsgroth** [comment]
It would be pretty easy to add a new hotkey that does this.

It also now occurs to me that "quit" is a poor name for the existing hotkey, so I'll change that name along with adding the new hotkey - probably something like "power off" would be more appropriate. I think I named it "quit" before I had implemented the GUI, when exiting the game was the same as exiting the application.

**Comment by jsgroth** [comment]
This is done in v0.8.3. The new hotkey is "Exit", and "Quit" has been renamed to "PowerOff"

**Comment by Tartifless** [comment]
Tops
