### ISSUE TITLE
Search rom

### ISSUE THREAD

**Issue by Chipsum** [jsgroth/jgenesis#15]
Hi, I am testing jgenesis for the first time, I scanned a whole no-intro set
Now I need a search bar to find a rom without scrolling to find it

**Comment by jsgroth** [comment]
Hello,

In the current version you can click File > Open or press Ctrl+O to open an OS-native file dialog which should support search.

Putting a search/filter box on the main screen is a good idea though, I'll add that soon.

**Comment by Chipsum** [comment]
File > Open and search is irrelevant 
I am talking about after scanning a directory (importing ROMs)
![image](https://github.com/jsgroth/jgenesis/assets/37517008/272a8cb7-b6de-4b3f-b1d7-6bf659062439)

**Comment by jsgroth** [comment]
#16 adds a search box to the ROM list panel. Is this what you meant?

![Screenshot from 2023-12-15 16-50-39](https://github.com/jsgroth/jgenesis/assets/1137683/f9ef6010-988a-4419-adb8-6c35902aec9c)


I've attached current builds from https://github.com/jsgroth/jgenesis/actions/runs/7227869917 if you want to test before the next published release:
[jgenesis-0.6.0-DEV-linux-x86_64.tar.gz](https://github.com/jsgroth/jgenesis/files/13690292/jgenesis-0.6.0-DEV-linux-x86_64.tar.gz)
[jgenesis-0.6.0-DEV-windows-x86_64.zip](https://github.com/jsgroth/jgenesis/files/13690305/jgenesis-0.6.0-DEV-windows-x86_64.zip)

**Comment by Chipsum** [comment]
That's exactly what I mean

**Comment by Chipsum** [comment]
it's working fine 👍 
![image](https://github.com/jsgroth/jgenesis/assets/37517008/350932b4-dbf0-4d02-8045-fbe021ec294b)
