### ISSUE TITLE
(MD) single-screen interlace mode seemingly acts as double-screen interlace

### ISSUE THREAD

**Issue by RealMalachi** [jsgroth/jgenesis#17]
I can already see like 95% of megadrive devs doing a double take, so let me explain.
The Megadrive has three interlace rendering modes: single screen progressive (the one used in most games), double screen interlace (used in Sonic 2s and Combat Cars' 2 player modes), and single screen interlace (used for Xband console syncing, and Ys III apparently). [This mode is acknowledged in the genesis software manual](https://segaretro.org/index.php?title=File%3AGenesis_Software_Manual.pdf&page=22), which is a little funny considering it was in your sources
Aside for BlastEm, I'm pretty sure most emulators just make single interlace use progressive. This emulator, however, seems to use double screen interlace, or have some other misc error with single interlace

Since I honestly don't care enough for Ys III, the pictures shown are of a hacked version of Sonic 2 (I added it as a debug feature, like "night mode" but less novel). Sorry for the big size
![image](https://github.com/jsgroth/jgenesis/assets/118614564/f36314a0-b546-440c-bde4-6589556bd899)

Prohibited interlace rendering seems to be using 8x8 tiles (it's using 2P code so it's trying to render 8x16). While this is to be expected for most hardware (my VA6 looks practically identical to the screenshot), this could mean you're accidentally checking LSM0 instead of LSM1. If you want a quick fix, because no games are even meant to use prohibited rendering, that's probably how you do it
![image](https://github.com/jsgroth/jgenesis/assets/118614564/39a3f256-0056-4466-a968-ffa95f78de3e)

**Comment by jsgroth** [comment]
> this could mean you're accidentally checking LSM0 instead of LSM1

This is pretty much it, there's a missing bit shift that causes the screen mode check to read bits LSM0+RS1 instead of LSM1+LSM0. The intent was for single-screen interlaced mode to behave the same as progressive mode. Thanks for pointing this out, nothing I tested ever used single-screen interlaced.

**Comment by jsgroth** [comment]
I just published a new release which includes this fix:
https://github.com/jsgroth/jgenesis/releases/tag/v0.7.0
