### ISSUE TITLE
Initial D Gaiden (Japan) (SGB Enhanced).gb fails to boot

### ISSUE THREAD

**Issue by benderscruffy** [jsgroth/jgenesis#28]

**Comment by jsgroth** [comment]
The fix for #27 also fixes this game failing to boot, but it now crashes when starting a race so this isn't really fixed yet. My initial guess is incorrect PPU mode 3 timing.

**Comment by jsgroth** [comment]
This one is puzzling.

It seems that there's an edge case to the DMG STAT write/interrupt hardware bug where it doesn't always trigger when it should. As best as I can tell, the spurious interrupt is suppressed when HBlank STAT interrupts were previously enabled and the STAT write occurs during mode 2 (OAM scan). This fixes Initial D Gaiden without breaking Zerd no Densetsu or Road Rash, and it matches the behavior that I see for this game in SameBoy via debugger.
