### ISSUE TITLE
LEGO Racers (Europe) (En,Fr,De,Es,It,Nl,Pt,Sv,No,Da).gbc freezes up on the language select screen

### ISSUE THREAD

**Issue by benderscruffy** [jsgroth/jgenesis#29]

**Comment by jsgroth** [comment]
This game seems to work mostly correctly after the fix for #27, but there's a bit of flickering during gameplay which I think is probably related to incorrect PPU mode 3 timing.

**Comment by jsgroth** [comment]
The flickering colors during gameplay were caused by blocking CPU access to VRAM + CGB palettes one M-cycle too early. The timings sometimes line up such that the game finishes modifying palettes exactly on the last possible M-cycle before the PPU starts rendering pixels.
