### ISSUE TITLE
Little Mermaid II, The - Pinball Frenzy (USA) (En,Fr,De,Es,It) (Rumble Version).gbc corrupt graphics

### ISSUE THREAD

**Issue by benderscruffy** [jsgroth/jgenesis#35]

**Comment by jsgroth** [comment]
This game initiates HDMAs during HBlank and it seems to expect them to begin immediately rather than waiting for the start of HBlank on the next line. Otherwise some of the HDMAs will end up copying data into the wrong VRAM bank which causes the corrupted graphics.
