### ISSUE TITLE
Ken Griffey Jr.'s Slugfest (USA).gbc corrupt graphics during home run derby

### ISSUE THREAD

**Issue by benderscruffy** [jsgroth/jgenesis#37]

**Comment by jsgroth** [comment]
This game depends on HBlank STAT interrupts not blocking LY=LYC STAT interrupts when both are enabled (and mode 2 STAT interrupts are not enabled). Missing the LY=LYC interrupts causes it to skip its mid-frame BG palette updates in roughly 2 out of every 3 frames.
