### ISSUE TITLE
Rockman X3 (Taiwan) (En) (Unl).md  Game doesn't boot due to "DECODE ERROR

### ISSUE THREAD

**Issue by benderscruffy** [jsgroth/jgenesis#60]

**Comment by jsgroth** [comment]
From info that's available online about this game, this seems to be some sort of anti-piracy or integrity check within the game code. Before it crashes I see it do two reads from $A13000 which is normally an unmapped address, so maybe it's expecting those reads to return specific values.

**Comment by jsgroth** [comment]
This boots and is playable if I make $A13000 reads return $000C (or really any value where the lowest 4 bits are $C):
![Screenshot from 2024-05-08 15-55-12](https://github.com/jsgroth/jgenesis/assets/1137683/2841cfab-a85a-47f9-90bd-4255567a5abc)

The in-game graphics are quite glitchy but I think that's just the game.
