### ISSUE TITLE
Cybernoid - The Fighting Machine (USA).nes graphic glitches

### ISSUE THREAD

**Issue by benderscruffy** [jsgroth/jgenesis#79]
Start the game then next pause the game and press A you will see graphics errors when the music starts to play.

**Comment by jsgroth** [comment]
This is one of the few games (maybe the only game) that depends on mapper bus conflicts, which were not previously emulated:
https://www.nesdev.org/wiki/INES_Mapper_003#Notes

On certain cartridge boards, CPU writes to mapper registers in $8000-$FFFF are bitwise ANDed with the value at that address in PRG ROM. Other games work around this by only writing to addresses where the value in ROM matches what is being written (or is $FF). Cybernoid however depends on this bus conflict behavior or else it will erroneously change the CHR ROM bank from 0 to 3 in its audio code, and then it will never recover from that.
