### ISSUE TITLE
Robopon - Sun Version (USA) (SGB Enhanced) (GB Compatible).gbc unsupported mapper byte

### ISSUE THREAD

**Issue by benderscruffy** [jsgroth/jgenesis#89]

**Comment by jsgroth** [comment]
The mapper byte in the header is $FE which is Hudson's custom HuC-3 mapper, not currently emulated:
https://gbdev.io/pandocs/HuC3.html

This seems to be the only HuC-3 (or HuC-1) game that released outside of Japan.

The ROM/RAM banking looks trivial to emulate (it's basically the same as MBC3/MBC5), but this mapper has a real-time clock with a much more complex command/communication protocol than the MBC3 RTC. There's also a builtin speaker with a tone generator that doesn't seem to be well-understood/documented - [this GBDev thread](https://gbdev.gg8.se/forums/viewtopic.php?id=744) suggests that the tone generator behavior comes from a microcontroller program ROM that likely varies between different HuC-3 cartridges.

I'm probably not going to try to emulate the speaker/tone generator but the rest of this mapper seems doable.

**Comment by jsgroth** [comment]
The HuC-3 ROM/RAM banking and RTC are now emulated, which is enough for Robopon to work.

The following features of this mapper are not currently emulated:
* The speaker built into the cartridge and the associated tone generator
* The IR sensor built into the cartridge
* Some sort of alarm/event functionality related to the RTC that is not well-documented (or maybe just not well-understood)
